# gitpod configuration
# https://www.gitpod.io/docs/config-docker/#configure-a-custom-docker-image
image: python:3.8-buster

vscode:
  # https://www.gitpod.io/docs/vscode-extensions/#installing-an-extension
  extensions:
    - ms-python.python@2020.4.76186
    # https://marketplace.visualstudio.com/items?itemName=ms-python.python
    # requires mypy, black, and flake8
    - timonwong.shellcheck@0.9.0
      # https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck
      # requires a shellcheck executable
    - editorconfig.editorconfig@0.145

# https://www.gitpod.io/docs/config-start-tasks/#start-tasks
tasks:
  - before: apt-get update && apt-get install -y shellcheck
  - before: python3 -m pip install pipenv
    command: pipenv install --dev && source ./.venvs/code-challenge-python-environment/bin/activate
  - command: export PYTHONPATH="$(pwd)/src:$PYTHONPATH"

github:
  prebuilds:
    master: true
