# gitpod configuration
# https://www.gitpod.io/docs/config-docker/#configure-a-custom-docker-image
image: python:3.8-buster

vscode:
  # https://www.gitpod.io/docs/vscode-extensions/#installing-an-extension
  extensions:
    - ms-python.python@2020.4.76186
    # https://marketplace.visualstudio.com/items?itemName=ms-python.python
    # requires mypy, black, and flake8
    - timonwong.shellcheck@0.9.0
      # https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck
      # requires a shellcheck executable
    - editorconfig.editorconfig@0.145

# https://www.gitpod.io/docs/config-start-tasks/#start-tasks
tasks:
  - command: apt-get update && apt-get install shellcheck
  - command: |
      python3 -m pip install pipenv &&
        pipenv sync &&
        pipenv shell
  - command: export PYTHONPATH="$(pwd)/src:$PYTHONPATH"
